# Generated by Django 3.0 on 2019-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgaver',
            name='noter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
