# Generated by Django 3.0 on 2019-12-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0002_auto_20191215_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opgaver',
            old_name='noter',
            new_name='testnoter',
        ),
    ]
