# Generated by Django 3.0 on 2019-12-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0003_auto_20191215_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opgaver',
            old_name='testnoter',
            new_name='noter',
        ),
    ]
