# Generated by Django 2.0.7 on 2019-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0005_auto_20191231_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunder',
            name='kunde_installation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
