# Generated by Django 2.0.7 on 2020-01-02 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opgaver', '0007_auto_20191231_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kunder',
            options={'ordering': ('kunde_navn',)},
        ),
        migrations.AlterModelOptions(
            name='opgaver',
            options={'ordering': ('prioritet', 'deadline')},
        ),
        migrations.AddField(
            model_name='opgaver',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='prioritet',
            field=models.IntegerField(choices=[(1, 'Højeste'), (2, 'Mellem'), (3, 'Laveste')], default=3),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ikke angivet'), (2, 'Startet'), (3, 'Halvvejs'), (4, 'Sidste Detaljer'), (5, 'Færdig')], default=1),
        ),
    ]
